kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pensjon-opptjening-hendelse-api-q1
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: pensjon-popp-q1
          namespace: pensjonopptjening
          cluster: dev-fss
        - application: poppbatch-q
          namespace: pensjon-batch
          cluster: dev-fss
  kafka:
    pool: nav-dev
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: dev-gcp
    - name: BEHOLDNING_ENDRET_TOPIC
      value: pensjonopptjening.beholdning-endret-topic-q1
    - name: OPPTJENING_ENDRET_TOPIC
      value: pensjonopptjening.opptjening-endret-topic-q1
  image: {{ image }}
  ingresses:
    - https://pensjon-opptjening-hendelse-api-q1.intern.dev.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
  prometheus:
    enabled: true
    path: /actuator/prometheus
  observability:
    autoInstrumentation:
      enabled: true
      runtime: java
    logging:
      destinations:
        - id: secure_logs
  replicas:
    min: 1
    max: 4
    scalingStrategy:
      cpu:
        thresholdPercentage: 75
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi