kind: Application
apiVersion: nais.io/v1alpha1
metadata:
  name: pgi-endring
  namespace: pensjonopptjening
  labels:
    team: pensjonopptjening
spec:
  azure:
    application:
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: pgi-endring-proxy
          namespace: pensjonopptjening
          cluster: prod-fss
        - application: pensjon-popp
          namespace: pensjonopptjening
          cluster: prod-fss
  kafka:
    pool: nav-prod
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod-gcp
    - name: KAFKA_PGI_ENDRING_TOPIC
      value: pensjonopptjening.pgi-endring-topic
  image: {{ image }}
  ingresses:
    - https://pgi-endring.intern.nav.no
  liveness:
    path: /internal/isalive
    port: 8080
    initialDelay: 40
  readiness:
    path: /internal/isready
    port: 8080
    initialDelay: 40
  prometheus:
    enabled: true
    path: /actuator/prometheus
  replicas:
    min: 3
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: "4"
      memory: 8096Mi
    requests:
      cpu: 400m
      memory: 4024Mi