name: Bygg og deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build_and_push:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v6

      - name: 'Setup Java'
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 25
          cache: 'gradle'

      - name: 'Setter git-referansetag'
        run: |
          echo "GIT_REF_TAG=git_${{github.ref_name}}_$(echo ${{github.sha}} | cut -c 1-7)" >> $GITHUB_ENV

      - name: 'Generate and submit dependency graph'
        uses: gradle/actions/dependency-submission@v6
        with:
          dependency-graph-include-configurations: '^runtimeClasspath$'

      - name: 'Build code'
        run: ./gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push docker image'
        uses: nais/docker-build-push@v0
        id: docker-push
        with:
          team: pensjonopptjening
          tag: ${{env.GIT_REF_TAG}}

      - name: 'Deploy til dev-gcp'
        uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: nais/dev-gcp-q0.yml,nais/dev-gcp-q1.yml,nais/dev-gcp-q2.yml,nais/dev-gcp-q5.yml
          CLUSTER: dev-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}

      - name: 'Deploy to prod-gcp'
        if: ${{github.ref == 'refs/heads/master' }}
        uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: nais/prod-gcp.yml
          CLUSTER: prod-gcp
          IMAGE: ${{ steps.docker-push.outputs.image }}
          TELEMETRY: ${{ steps.docker-push.outputs.telemetry }}
