name: Deploy topics prod-gcp

on:
  push:
    branches:
      - master
    paths:
      - 'nais/topics/pgi-endring-topic-prod-gcp.yaml'
jobs:
  deploy_topics:
    permissions:
      contents: "read"
      id-token: "write"  
    name: 'Deploy topics'
    runs-on: ubuntu-latest
    steps:
      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v2

      - name: 'Deploy topic to prod-gcp'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/topics/pgi-endring-topic-prod-gcp.yaml
