name: Deploy topics prod-gcp

on:
  push:
    branches:
      - master
jobs:
  deploy_topics:
    permissions:
      contents: "read"
      id-token: "write"  
    name: 'Deploy topics'
    runs-on: ubuntu-latest
    steps:
      - name: 'Pull repo'
        uses: actions/checkout@v4

      - name: 'Deploy'
        uses: nais/deploy/actions/deploy@v2
        env:
          CLUSTER: prod-gcp
          RESOURCE: nais/topics/opptjening-endret-topic.yaml
