name: Bygg og deploy til prod-gcp

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'nais/topics/pgi-endring-topic-dev-gcp-q0.yaml'
      - 'nais/topics/pgi-endring-topic-dev-gcp-q1.yaml'
      - 'nais/topics/pgi-endring-topic-dev-gcp-q2.yaml'
      - 'nais/topics/pgi-endring-topic-dev-gcp-qdiv.yaml'
      - 'nais/topics/pgi-endring-topic-prod-gcp.yaml'
      - 'nais/dev-gcp-q0.yml'
      - 'nais/dev-gcp-q1.yml'
      - 'nais/dev-gcp-q2.yml'
      - 'nais/dev-gcp-qdiv.yml'
      - 'README.md'
jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v1

      # SETTER DATO OG COMMIT VARIABEL
      - name: 'Setter dato og commit variabel'
        run: |
          export TZ=CET
          echo "DATE=$(date "+%Y-%m-%d--%H-%M-%S")" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
      # SETTER IMAGE VARIABEL
      - name: 'Setter Image'
        run: echo "IMAGE=docker.pkg.github.com/${{ github.repository }}/pgi-endring:${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_ENV

      # JAVA 17
      - name: 'Java 17'
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 17

      # BYGGER DOCKER CONTAINER
      - name: 'Bygg og publiser docker image'
        run: |
          ./gradlew build
          docker build --tag ${{ env.IMAGE }} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${{ secrets.GITHUB_TOKEN }}
          docker push ${{ env.IMAGE }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # DEPLOYER TIL NAIS prod-gcp team namespace
      - name: 'Deploy pgi-endring to prod-gcp'
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          RESOURCE: nais/prod-gcp.yml
          CLUSTER: prod-gcp
          IMAGE: ${{ env.IMAGE }}
